services:
  postgres-filemeta:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: harvester
      POSTGRES_PASSWORD: yoursecretsecret
    volumes:
      - postgres_filemeta_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U harvester -d admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  pipeline-runner:
    build:
      context: .
      dockerfile: pipelines.Dockerfile
    depends_on:
      postgres-filemeta:
        condition: service_healthy

    volumes:
      - ./src:/app/src
      - ./deployments:/app/deployments
      - ./config/config-docker.toml:/app/config/config.toml
      - ./config/harvester.toml:/app/config/harvester.toml
    working_dir: /app
    command: uv run python -m filemeta_harvester.flows.harvester_flows

volumes:
  postgres_filemeta_data:
